### ISSUE TITLE
Field mapping for timestamp results no timestamp or date

### ISSUE THREAD

**Issue by marck-consulting** [bobdenotter/forms#12] opened 2020-10-04 14:30 UTC
Mapping ‘timestamp’ into a contenttype field results in:
Text field: 00000000423a013000000000110df7d6
Date field: Empty date selector

**Comment by ghost** [comment] 2021-05-13 02:30
Issue confirmed on Bolt 4.1.19 using Forms 1.4.1.

**Comment by bobdenotter** [comment] 2021-06-15 17:23
This should be fixed in the next release.. For me it looks like this now: 

![Screenshot 2021-06-15 at 19 13 10](https://user-images.githubusercontent.com/1833361/122096702-1f4e7980-ce0f-11eb-908b-03c1f3cf461f.png)

**Closed as completed by bobdenotter** 2021-06-15 17:23 UTC
